spring:
  application:
    name: BOOOKING-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27017/Bookingdb
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
server:
  port: 8200
  
  